### ISSUE TITLE
rdr-bridgeのハンドリング

### ISSUE THREAD

**Issue by h-takeyeah** [su-its/ams-backend-nodejs#15]
controllerのうちカードのタッチに反応してrdr-bridgeがこちらに投げてくるPOSTをハンドルするreaderInputControllerについてです．以下の部分になります．

https://github.com/su-its/ams-backend-nodejs/blob/8a4dd0d12db5669db90ab16efcf1ce0910fd1add/app/controllers/readerInputController.ts#L7-L22

18行目を見てください．このif文は正常な場合もはねてしまいます(statusが'success'⇒user_idはnumber，statusが'success'以外⇒user_idがnull，これが正常な動作)．rdr-bridgeの以下のコードを見ればわかる通りuser_idはともかくstatusは必ず設定されてPOSTされるわけです．

https://github.com/su-its/rdr-bridge/blob/c7d324a5548f1067fb6ddc2bc08fc945ec2b9535/main.py#L27-L42

ですから，例外をはねるなら

```javascript
if (!readerStatus) {
  // エラー音的なsomethingを鳴らしたりログを取ったり
  return
}
```

になろうかと思います．あるいはこれに加えてreaderStatusが定数Status<'success' | 'error' | 'fatal'>に存在するかどうかチェックするのもいいかもしれません．

それと55行目のエラーは握りつぶされているので，何かしたいですね．
https://github.com/su-its/ams-backend-nodejs/blob/8a4dd0d12db5669db90ab16efcf1ce0910fd1add/app/controllers/readerInputController.ts#L39-L57

**Comment by equal-l2** [comment]
どのif文がどんなエラーを弾きたいのかコメントで書いといたらいいですね

**Comment by h-takeyeah** [comment]
いまそれっぽいコードを錬成したのでPRします

**Comment by Stroheim001** [comment]
@equal-l2 @h-takeyeah 頓珍漢な事だったら申し訳ないのですが、statusがsuccess以外のものが来た時はそれ用のlogを吐かせるのはエラーハンドリングとしてあったほうが問題解決が早くなると思います。採用するかは、お任せします。

**Comment by h-takeyeah** [comment]
@Stroheim001 ありがとうございます．分かりにくいとは思いますが，一応[`03f792c`](https://github.com/su-its/ams-backend-nodejs/tree/03f792c2b7c28c4962435204dbc35ffbac21447d)のコミットでブリッジからのstatusごとにlogを吐くように変更しました．確認お願いします．

https://github.com/su-its/ams-backend-nodejs/pull/16/commits/03f792c2b7c28c4962435204dbc35ffbac21447d#diff-fca2ddc087462062123a28511e244e5551db0822c7e01f45e235150e4f61f3cbL49-L59

**Comment by Stroheim001** [comment]
@h-takeyeah 返信遅くなってすみません。えっと、logは確かに吐いてるのですが、言いたいことは `console.log` ではなく、ファイルとして、時間とエラー内容などの4W1Hが出力されることを意図しています。

一応、consoleから出来なくはないらしいですが、それらしいものを発見できなかったので、報告させて頂きます。

**Comment by h-takeyeah** [comment]
@Stroheim001 そういうことでしたか．想像力が足りず申し訳ありません．ファイルに4W1Hを付加して出力させるべきという意見には賛成です．現状では，`console.log`および`console.error`の内容はpm2のログとして吐き出されるようになっているはずです．ただ，whenの情報は行頭に付加されるようなのですが，それ以外は`console.log`および`console.error`の内容を実直に記録するだけなので4W1Hは満たせていないです．そこのところpm2に吐き出すログをもう少し工夫出来たらしてみます．
