### ISSUE TITLE
フロントエンドへのイベント通知

### ISSUE THREAD

**Issue by equal-l2** [su-its/ams-backend-nodejs#17]
WebSocketのエンドポイントを用意する

**Comment by h-takeyeah** [comment]
[h-takeyeah/nodews](https://github.com/h-takeyeah/nodews)
テスト用のコードを書きました．よかったらWebSocketのテストにどうぞ．ams-frontendと組み合わせると使えると思います．ams-frontendのtestingブランチです

**Comment by Stroheim001** [comment]
@equal-l2 @h-takeyeah 
openAPIからテキトーにデータ返せないか考慮してみます。ただ、VPS等がいるかもしれないので予算がいるかもしれません。

個人的には、bou_relayが置かれている鯖に同居させてもらえるとどこからでもテスティング出来るんじゃないかと思ってます。

(が、判断は任せます)

**Comment by h-takeyeah** [comment]
bou-relayはGASです。可能だと思います

**Comment by h-takeyeah** [comment]
[Server-Sent events(SSE)](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events) にて実装中です．
