### ISSUE TITLE
Docker上のDB接続時のエラー

### ISSUE THREAD

**Issue by equal-l2** [su-its/ams-backend-nodejs#24]
バックエンド起動時にDBに接続できないとその場で死ぬ
(docker-composeで実行するとDBコンテナが立ち上がる前にバックエンドコンテナが動き出す場合があるので困る)

**Comment by Stroheim001** [comment]
@equal-l2 
docker-compose.ymlの `links` 部を `depend_on` に変えれば治ると思う(それがbuildの順序を決めるので)のですが、自分の環境ではそもそも該当のエラーが生じてないので、申し訳ないのですが、完成した後実験してもらえると助かります。

**Comment by equal-l2** [comment]
シンプルにconfig.tsの設定が間違ってました……
(ホスト名を `db` にしてなかったのでそもそも接続相手がいなかった)

**Comment by Stroheim001** [comment]
@equal-l2 あれ？contribute.mdに書いてたつもりだけど、もっと強調したほうが良かった感じ？

**Comment by equal-l2** [comment]
自分でもおかしいとは思うんですが、日本語が読めてなかっただけでした
