### ISSUE TITLE
API仕様書と実際のソースコードが乖離している(表記ゆれ)

### ISSUE THREAD

**Issue by Stroheim001** [su-its/ams-backend-nodejs#28]
userIdとuser_idで表記ゆれを起こしており、APIのエンドポイントから利用する側にとっては非常に不便である。

**Comment by h-takeyeah** [comment]
userIdの件は文法上は許容される表記ゆれでした．しかし，TSの規約的にキャメルケースで書いたとはいえ，外から入ってくるデータがスネークケースではないのは気持ち悪いので`inRoomUsersRoutes.ts`内のuserIdはuser_idと書き直しました．それに伴って`inRoomUsersController.ts`も修正しました．

今回のように2つのファイルを読まないと文法上許容されることが分からないのはバグのもと，いやバグだったので以後気を付けます．
