### ISSUE TITLE
音声周りのデバッグに関して

### ISSUE THREAD

**Issue by Stroheim001** [su-its/ams-backend-nodejs#30]
完全にwin開発者向けの話になってしまいますが、音声を鳴らすために必要な操作が `alsa` は `pulseaudio` に比べて非常に大変になっています。

そこでなのですが、音声をalsaからpulseaudioに移管することはできないでしょうか？？？

**Comment by Stroheim001** [comment]
alsaからpulseaudioに変えるコストよりもエラーハンドリングを重視したいと考え、

音声が流れないは仕方がないとして、SQL文が流れてないのは問題なので、正しく動作を保証するためにこのエラーハンドリングの実装を要求します。

**Comment by h-takeyeah** [comment]
@Stroheim001 手元で試してみたところ以前のコードのままでもchild_processが落ちたことに伴ってSQLクエリが発行されない現象を再現することができませんでした．child_process#spawnSync()について調べ，エラーが出たときに確実にログに出せるようにしたつもりです．

自分の手元で出鱈目なコマンドを実行させて意図したとおりのエラーメッセージが表示されることは確認しました．ただ，先に述べた通りこの修正をする前もした今でも，SQLクエリが発行されないということはなかったので，この方法で本当に動作が安定するのか分かりません．@Stroheim001 さんの手元で実験してみていただければと思います．
