### ISSUE TITLE
readerInputControllerのエラー時にレスポンスが戻ってこないことがある

### ISSUE THREAD

**Issue by equal-l2** [su-its/ams-backend-nodejs#33]
ここと

https://github.com/su-its/ams-backend-nodejs/blob/9dac97a8d92fcd47088c4a48151202f1fd6a8b5d/app/controllers/readerInputController.ts#L75-L78

ここ

https://github.com/su-its/ams-backend-nodejs/blob/9dac97a8d92fcd47088c4a48151202f1fd6a8b5d/app/controllers/readerInputController.ts#L92-L97

レスポンスを返してないので、エラーになると~フロント~rdr-bridgeが固まります。

**Comment by h-takeyeah** [comment]
了解しました．修正します．

**Comment by equal-l2** [comment]
Fixed in #39
