### ISSUE TITLE
ページネーションに必要な情報が足りない、または違う

### ISSUE THREAD

**Issue by Stroheim001** [su-its/ams-backend-nodejs#61]
とりあえずページネーションで、暫定的に作ってもらったAPIですが、meta情報に不足があり、代替手段で対応してますが、

仕様変更に弱くなっています。そこでAPIに修正を加えてほしいと思っています。

そんなに大変な作業ではないと思うので、すぐ終わるとは思います。

一応現行の仕様で通そうと思えば暫定的な対応でもなんとかならなくはないです。

変更して欲しい内容は以下になります

access_logsのmeta情報内の
- total_pageをtotalにして、全ての情報件数にして欲しい
- 仕様変更に耐えれるよう、per-pageという情報を追加し、このページはいったい何件のdataが入っているか分かるようにして欲しい。

**Comment by h-takeyeah** [comment]
`total_page`は`total`と`per_page`から計算できるから`total`にしてくれという要望ですか？
また総件数を表す`total`を追加した後も今までの`total_page`を残すのはありでしょうか？

**Comment by h-takeyeah** [comment]
@Stroheim001 念のため確認します．`per_page`はdata.lengthと同じ大きさということでよいのですよね．

例えば総件数が25件だった場合1ページ目の`per_page`は20，2ページ目の`per_page`は5になるということですよね．

---

ただバックエンド内部で`DATA_PER_PAGE`(=20)という定数が使用されており，これと若干混ざるなあと思っています．

**Comment by Stroheim001** [comment]
@h-takeyeah 
data.lengthが個数と同じという認識であっていればその通りです。
totalは確実に用意しておいてほしいです。
total_pageは放置でも構いません。
per_pageの最後の端数については、buefyのサンプルが不親切すぎて書いてないので分からないのですが、デフォだとどれくらいか、を書いて欲しいだけだと思いますが、最悪書かなくても良いと思います。

**Comment by h-takeyeah** [comment]
@Stroheim001 buefyのサンプル見ました．2点質問があります．下記の動作は`nuxt-sse`ブランチの
[API](https://buefy.org/documentation/pagination#api-view)によると確かに`per-page`にはそのページの行数を与えてあげれば良さそうですね．端数に関しては確かに謎ですね．

それとは別に`current`というのもあってこちらはバックエンドから渡されてくる`meta`の名称で言うと`page`にあたる情報を与えてあげれば良さそうですね．ただ現時点でのフロントエンドのじっそうには，この`current`が無いようですが付ける予定はありますか？というのが1点目の質問です．

で，もしつけるなら，バックエンドから渡す`meta`の`page`を`current`に名称変更したほうが分かりやすいかと思いますがどうしましょうか？というのが2点目です．

よろしくお願いします．


余談

https://github.com/su-its/ams-frontend/blob/2602b097f261c2209127cfca7a0c1e00e462970a/pages/log.vue#L10-L17

ここで`:per-page="10"`と指定しているのに描画されるのが20行というのはよく分かりません．まあそれは置いておいて

**Comment by Stroheim001** [comment]
@h-takeyeah 

v-modelの存在を勘違いされてるのではないかと思うのですが、そもそもcurrentはバックエンドと一切関係なく独立して動作しています。

個人的には、今誰がどのページを参照しているかなどという情報を保持している必要性を感じません(頓珍漢な発言だったらごめんなさい)

metaの名前を変えるについては可読性の問題ですので、正直「どうでも良い」が感想です。

ドキュメンテーションできちんと保管できるなら多少難しい名称でも十分ですし、逆に簡素な名前でも、ドキュメンテーションが言ってることと違うみたいな悲惨な状態なら、大問題だよ、ってのが感想です。

per-pageはちょっとなんとかならないか聞いてみます。20件はWQHDでもスクロールが必要なレベルなので

**Comment by h-takeyeah** [comment]
@Stroheim001 もしかしたら誤解されているかもしれないので補足します．

自分が言っている`current`というのは，フロントエンドのコードに書かれている
```
<b-pagination
  v-model="current_page"
```
この`current_page`ではなくて，[Buefy の API](https://buefy.org/documentation/pagination#api-view)に書かれているこれ

Name | Description | Type | Values | Default
-- | -- | -- | -- | --
current | Current page number, use the .sync modifier to make it two-way binding | Number | — | 1

のことを指しています．その点を把握したうえでの

> v-modelの存在を勘違いされてるのではないかと思うのですが、そもそもcurrentはバックエンドと一切関係なく独立して動作しています。

というコメントだったならすみません．もしそのようには把握していなかったら改めてコメントお願いします．

**Comment by h-takeyeah** [comment]
多分なんですけど[Buefy の API](https://buefy.org/documentation/pagination#api-view)に書かれている`current`は単に今このページが全体の何ページ目かという数字を格納するものです．

Googleの検索結果画面で言うと

Google >
**1** 2 3 次へ

の太字の1がそうです．

**Comment by Stroheim001** [comment]
@h-takeyeah 自分も忘れてることあるので、ちゃんと調べて教えられるようにしておきます。
