### ISSUE TITLE
Redpenの句読点の設定

### ISSUE THREAD

**Issue by equal-l2** [su-its/ams-backend-nodejs#68]
「、。」と「，．」、どちらにしましょうか。
#66 で「、。」が紛れ込んでしまった（CIの不具合）ので、この機会にちゃんと決めてCONTRIBUTING.mdに書こうと思います。

---

個人的にはどちらでもいいですが、今回のメンツには「，．」派がいないので、強いて決めるなら「、。」かなとは思います。

**Comment by Stroheim001** [comment]
@equal-l2 句点、句読点を切り替えるのは `variant="zenkaku2"` を削除するだけですが、PRだしときますね。

正直、自分も句点はともかく句読点に「、」を使えないのは厳しいです。

**Comment by equal-l2** [comment]
句読点の設定変更と一緒に文書内の句読点の置き換えもやっちゃいたいので、自分がPR立てようと思います。
